# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 📦 Publish to NPM

on:
    release:
        types: [created]

jobs:
    publish-npm:
        name: 🚀 Publish to NPM
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
            - name: 📦 Install dependencies
              uses: oven-sh/setup-bun@v1
            - run: bun install
              name: 🧶 Install dependencies
            - run: bun run build
              name: 🏗️ Build
            - run: bun publish
              name: 📮 Publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
